# Generated by Django 5.2.17 on 2026-09-25 14:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Код (латиницей)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Частые вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('perk', 'Преимущество (тёмная полоса)'), ('step', 'Шаг «Как заказать»')], max_length=10, verbose_name='Блок')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Карточка блока',
                'verbose_name_plural': 'Преимущества и шаги заказа',
                'ordering': ['kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Имя автора')),
                ('product_name', models.CharField(blank=True, max_length=120, verbose_name='Изделие')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('photo', models.ImageField(blank=True, upload_to='reviews/', verbose_name='Фото')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на оригинал')),
                ('visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='GLÜCKSTAL', max_length=60, verbose_name='Название бренда')),
                ('master_name', models.CharField(blank=True, max_length=80, verbose_name='Имя мастера')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s()-]{10,20}$', 'Телефон: 10–15 цифр, с кодом страны')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telegram', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]{4,}$', 'Только ник, без @ и ссылки')], verbose_name='Telegram (ник без @)')),
                ('vk_url', models.URLField(blank=True, verbose_name='Ссылка на VK')),
                ('whatsapp', models.CharField(blank=True, help_text='Если заполнено — на сайте появится кнопка WhatsApp', max_length=30, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s()-]{10,20}$', 'Телефон: 10–15 цифр, с кодом страны')], verbose_name='WhatsApp (номер)')),
                ('old_site_url', models.URLField(blank=True, help_text='Показывается в подвале', verbose_name='Ссылка на старый сайт')),
                ('site_url', models.URLField(default='https://gluckstal.store', help_text='Для canonical, sitemap и превью ссылок', verbose_name='Адрес сайта')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='Заголовок вкладки / для поиска (title)')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='Описание для поиска (description)')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=120, verbose_name='Надзаголовок')),
                ('hero_title', models.CharField(blank=True, max_length=120, verbose_name='Главный заголовок')),
                ('hero_lead', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/', verbose_name='Главное фото')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Логотип (круглый, PNG с прозрачностью)')),
                ('about_title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок «Обо мне»')),
                ('about_text', models.TextField(blank=True, help_text='Абзацы — через пустую строку. **Жирный** — двумя звёздочками.', verbose_name='Текст «Обо мне»')),
                ('about_photo', models.ImageField(blank=True, upload_to='site/', verbose_name='Фото мастера')),
                ('workshop_photo', models.ImageField(blank=True, upload_to='site/', verbose_name='Фото мастерской')),
                ('custom_title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок блока «Своя модель»')),
                ('custom_text', models.TextField(blank=True, verbose_name='Текст блока «Своя модель»')),
                ('custom_photo', models.ImageField(blank=True, upload_to='site/', verbose_name='Фото блока «Своя модель»')),
                ('metrika_id', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Только цифры')], verbose_name='Номер счётчика Яндекс.Метрики')),
                ('bot_token', models.CharField(blank=True, max_length=120, validators=[django.core.validators.RegexValidator('^\\d{5,}:[A-Za-z0-9_-]{30,}$', 'Формат 123456789:AA…')], verbose_name='Токен Telegram-бота')),
                ('chat_ids', models.CharField(blank=True, help_text='Кому бот присылает заявки. Проще всего — кнопкой «Найти чаты» внизу страницы.', max_length=300, validators=[django.core.validators.RegexValidator('^\\s*(-?\\d{3,}|@\\w{5,})(\\s*,\\s*(-?\\d{3,}|@\\w{5,}))*\\s*$', 'Номера через запятую')], verbose_name='ID чатов для заявок')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Ссылка на товар будет вида /#p=код', max_length=60, unique=True, verbose_name='Код для ссылки (латиницей)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, ₽')),
                ('price_from', models.BooleanField(default=False, verbose_name='Цена «от»')),
                ('description', models.TextField(help_text='Каждый пункт — с новой строки. Первый пункт виден в карточке.', verbose_name='Описание')),
                ('for_him', models.BooleanField(default=False, verbose_name='Подарок мужчине')),
                ('for_her', models.BooleanField(default=False, verbose_name='Подарок женщине')),
                ('visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['order', 'id'],
            },
        ),
    ]
