# Generated by Django 5.2.17 on 2026-09-25 14:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('visitor', models.CharField(db_index=True, max_length=40, verbose_name='Посетитель')),
                ('started', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Начало')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('active_seconds', models.PositiveIntegerField(default=0, verbose_name='Время на сайте, сек')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('device', models.CharField(blank=True, max_length=120, verbose_name='Устройство')),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Тип устройства')),
                ('referrer', models.CharField(blank=True, max_length=300, verbose_name='Откуда пришёл')),
                ('source', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Источник')),
                ('landing', models.CharField(blank=True, max_length=300, verbose_name='Страница входа')),
                ('lang', models.CharField(blank=True, max_length=5, verbose_name='Язык')),
                ('screen', models.CharField(blank=True, max_length=20, verbose_name='Экран')),
                ('pageviews', models.PositiveIntegerField(default=1, verbose_name='Просмотры')),
                ('events', models.JSONField(blank=True, default=dict, verbose_name='События')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-started'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=60, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', verbose_name='Ответ (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=200, verbose_name='Вопрос (EN)'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='text_en',
            field=models.TextField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', verbose_name='Текст (EN)'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='title_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=80, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=120, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=80, verbose_name='Имя автора (EN)'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_name_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=120, verbose_name='Изделие (EN)'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', verbose_name='Текст отзыва (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', verbose_name='Текст «Обо мне» (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=120, verbose_name='Заголовок «Обо мне» (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bot_username',
            field=models.CharField(blank=True, help_text='Нужен для входа в админку через Telegram. Заполняется сам при «Найти чаты».', max_length=64, verbose_name='Username бота (без @)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='city_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=60, verbose_name='Город (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_text_en',
            field=models.TextField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', verbose_name='Текст блока «Своя модель» (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_title_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=120, verbose_name='Заголовок блока «Своя модель» (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=120, verbose_name='Надзаголовок (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_lead_en',
            field=models.TextField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', verbose_name='Подзаголовок (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=120, verbose_name='Главный заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='master_name_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=80, verbose_name='Имя мастера (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=300, verbose_name='Описание для поиска (description) (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Английская версия. Если пусто — на английской странице показывается русский текст.', max_length=160, verbose_name='Заголовок вкладки / для поиска (title) (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_api_url',
            field=models.URLField(blank=True, help_text='Пусто — https://api.telegram.org. Укажите адрес ретранслятора, если сервер не может напрямую связаться с Telegram.', verbose_name='Адрес Telegram Bot API'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='chat_ids',
            field=models.CharField(blank=True, help_text='Кому бот присылает заявки. Проще всего — кнопкой «Найти чаты» вверху страницы.', max_length=300, validators=[django.core.validators.RegexValidator('^\\s*(-?\\d{3,}|@\\w{5,})(\\s*,\\s*(-?\\d{3,}|@\\w{5,}))*\\s*$', 'Номера через запятую')], verbose_name='ID чатов для заявок'),
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Имя в Telegram')),
                ('linked', models.DateTimeField(auto_now_add=True, verbose_name='Привязан')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-аккаунт',
                'verbose_name_plural': 'Telegram-аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('contact', models.CharField(max_length=120, verbose_name='Контакт')),
                ('via', models.CharField(blank=True, max_length=20, verbose_name='Связаться через')),
                ('product', models.CharField(blank=True, max_length=120, verbose_name='Изделие')),
                ('comment', models.TextField(blank=True, verbose_name='Пожелания')),
                ('lang', models.CharField(blank=True, max_length=5, verbose_name='Язык сайта')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('work', 'В работе'), ('done', 'Выполнена'), ('cancel', 'Отменена')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('telegram', models.CharField(choices=[('sent', 'Отправлена в Telegram'), ('failed', 'Ошибка Telegram'), ('off', 'Бот не настроен')], default='off', max_length=10, verbose_name='Telegram')),
                ('telegram_error', models.CharField(blank=True, max_length=300, verbose_name='Ошибка Telegram')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.visit', verbose_name='Визит')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created'],
            },
        ),
    ]
